### ISSUE TITLE
Tag Message

### ISSUE THREAD

**Issue by shivakumarg06** [jabbera/vsts-git-release-tag#45] opened 2019-01-19 14:22 UTC
Hello Jabbera, 

Git Tag feature is really good and thanks for that, 

Also, if this feature as a option to add Git Message along with Tag, it will be really useful,

**Comment by jabbera** [comment] 2019-01-30 14:33
Hi, this is a dupe of: https://github.com/jabbera/vsts-git-release-tag/issues/12

I don't have any plans to implement it but would be willing to take a quality PR.

**Closed by jabbera** 2019-01-30 14:33 UTC
